import { Runtime } from '@sinclair/parsebox'
import { Assert } from 'test'

const Test = Assert.Context('Runtime.Parse.Ident')
Test('Should Ident 1', () => Assert.IsEqual(Runtime.Parse(Runtime.Ident(), ''), []))
Test('Should Ident 2', () => Assert.IsEqual(Runtime.Parse(Runtime.Ident(), '0'), []))
Test('Should Ident 3', () => Assert.IsEqual(Runtime.Parse(Runtime.Ident(), '#'), []))
Test('Should Ident 4', () => Assert.IsEqual(Runtime.Parse(Runtime.Ident(), '_'), ['_', '']))
Test('Should Ident 5', () => Assert.IsEqual(Runtime.Parse(Runtime.Ident(), ' _'), ['_', '']))
Test('Should Ident 6', () => Assert.IsEqual(Runtime.Parse(Runtime.Ident(), '_ '), ['_', ' ']))
Test('Should Ident 7', () => Assert.IsEqual(Runtime.Parse(Runtime.Ident(), ' _ '), ['_', ' ']))
Test('Should Ident 8', () => Assert.IsEqual(Runtime.Parse(Runtime.Ident(), '$'), ['$', '']))
Test('Should Ident 9', () => Assert.IsEqual(Runtime.Parse(Runtime.Ident(), ' $'), ['$', '']))
Test('Should Ident 10', () => Assert.IsEqual(Runtime.Parse(Runtime.Ident(), '$ '), ['$', ' ']))
Test('Should Ident 11', () => Assert.IsEqual(Runtime.Parse(Runtime.Ident(), ' $ '), ['$', ' ']))
Test('Should Ident 12', () => Assert.IsEqual(Runtime.Parse(Runtime.Ident(), 'A'), ['A', '']))
Test('Should Ident 13', () => Assert.IsEqual(Runtime.Parse(Runtime.Ident(), ' A'), ['A', '']))
Test('Should Ident 14', () => Assert.IsEqual(Runtime.Parse(Runtime.Ident(), 'A '), ['A', ' ']))
Test('Should Ident 15', () => Assert.IsEqual(Runtime.Parse(Runtime.Ident(), ' A '), ['A', ' ']))
Test('Should Ident 16', () => Assert.IsEqual(Runtime.Parse(Runtime.Ident(), 'A1'), ['A1', '']))
Test('Should Ident 17', () => Assert.IsEqual(Runtime.Parse(Runtime.Ident(), ' A1'), ['A1', '']))
Test('Should Ident 18', () => Assert.IsEqual(Runtime.Parse(Runtime.Ident(), ' A1'), ['A1', '']))
Test('Should Ident 19', () => Assert.IsEqual(Runtime.Parse(Runtime.Ident(), 'A1 '), ['A1', ' ']))
Test('Should Ident 20', () => Assert.IsEqual(Runtime.Parse(Runtime.Ident(), ' A1 '), ['A1', ' ']))
