import { Runtime } from '@sinclair/parsebox'
import { Assert } from 'test'

const Test = Assert.Context('Runtime.Parse.UnsignedNumber')

Test('Should UnsignedNumber 1', () => Assert.IsEqual(Runtime.Parse(Runtime.UnsignedNumber(), '-1'), []))
Test('Should UnsignedNumber 2', () => Assert.IsEqual(Runtime.Parse(Runtime.UnsignedNumber(), '-1.0'), []))
Test('Should UnsignedNumber 3', () => Assert.IsEqual(Runtime.Parse(Runtime.UnsignedNumber(), ' -.0'), []))
Test('Should UnsignedNumber 4', () => Assert.IsEqual(Runtime.Parse(Runtime.UnsignedNumber(), ''), []))
Test('Should UnsignedNumber 5', () => Assert.IsEqual(Runtime.Parse(Runtime.UnsignedNumber(), '01'), ['0', '1']))
Test('Should UnsignedNumber 6', () => Assert.IsEqual(Runtime.Parse(Runtime.UnsignedNumber(), ' 01'), ['0', '1']))
Test('Should UnsignedNumber 7', () => Assert.IsEqual(Runtime.Parse(Runtime.UnsignedNumber(), '01 '), ['0', '1 ']))
Test('Should UnsignedNumber 8', () => Assert.IsEqual(Runtime.Parse(Runtime.UnsignedNumber(), ' 01 '), ['0', '1 ']))
Test('Should UnsignedNumber 9', () => Assert.IsEqual(Runtime.Parse(Runtime.UnsignedNumber(), '0'), ['0', '']))
Test('Should UnsignedNumber 10', () => Assert.IsEqual(Runtime.Parse(Runtime.UnsignedNumber(), '0 '), ['0', ' ']))
Test('Should UnsignedNumber 11', () => Assert.IsEqual(Runtime.Parse(Runtime.UnsignedNumber(), ' 0'), ['0', '']))
Test('Should UnsignedNumber 12', () => Assert.IsEqual(Runtime.Parse(Runtime.UnsignedNumber(), ' 0 '), ['0', ' ']))
Test('Should UnsignedNumber 13', () => Assert.IsEqual(Runtime.Parse(Runtime.UnsignedNumber(), '100'), ['100', '']))
Test('Should UnsignedNumber 14', () => Assert.IsEqual(Runtime.Parse(Runtime.UnsignedNumber(), '100 '), ['100', ' ']))
Test('Should UnsignedNumber 15', () => Assert.IsEqual(Runtime.Parse(Runtime.UnsignedNumber(), ' 100'), ['100', '']))
Test('Should UnsignedNumber 16', () => Assert.IsEqual(Runtime.Parse(Runtime.UnsignedNumber(), ' 100 '), ['100', ' ']))
Test('Should UnsignedNumber 17', () => Assert.IsEqual(Runtime.Parse(Runtime.UnsignedNumber(), '0.1'), ['0.1', '']))
Test('Should UnsignedNumber 18', () => Assert.IsEqual(Runtime.Parse(Runtime.UnsignedNumber(), '0.1 '), ['0.1', ' ']))
Test('Should UnsignedNumber 19', () => Assert.IsEqual(Runtime.Parse(Runtime.UnsignedNumber(), ' 0.1'), ['0.1', '']))
Test('Should UnsignedNumber 20', () => Assert.IsEqual(Runtime.Parse(Runtime.UnsignedNumber(), ' 0.1 '), ['0.1', ' ']))
Test('Should UnsignedNumber 21', () => Assert.IsEqual(Runtime.Parse(Runtime.UnsignedNumber(), '100.1'), ['100.1', '']))
Test('Should UnsignedNumber 22', () => Assert.IsEqual(Runtime.Parse(Runtime.UnsignedNumber(), '100.1 '), ['100.1', ' ']))
Test('Should UnsignedNumber 23', () => Assert.IsEqual(Runtime.Parse(Runtime.UnsignedNumber(), ' 100.1'), ['100.1', '']))
Test('Should UnsignedNumber 24', () => Assert.IsEqual(Runtime.Parse(Runtime.UnsignedNumber(), ' 100.1 '), ['100.1', ' ']))
Test('Should UnsignedNumber 25', () => Assert.IsEqual(Runtime.Parse(Runtime.UnsignedNumber(), '100.1.1'), ['100.1', '.1']))
Test('Should UnsignedNumber 26', () => Assert.IsEqual(Runtime.Parse(Runtime.UnsignedNumber(), '100.1.1 '), ['100.1', '.1 ']))
Test('Should UnsignedNumber 27', () => Assert.IsEqual(Runtime.Parse(Runtime.UnsignedNumber(), ' 100.1.1'), ['100.1', '.1']))
Test('Should UnsignedNumber 28', () => Assert.IsEqual(Runtime.Parse(Runtime.UnsignedNumber(), ' 100.1.1 '), ['100.1', '.1 ']))
