import { Runtime } from '@sinclair/parsebox'
import { deepStrictEqual } from 'node:assert'

function Assert(left: unknown, right: unknown) {
  deepStrictEqual(left, right)
}
// prettier-ignore
describe('Token', () => {
  it('Empty', () => {
    Assert(Runtime.Token.Const('', ''), ['', ''])
    Assert(Runtime.Token.Const('', 'A'), ['', 'A'])
    Assert(Runtime.Token.Const('', '   A'), ['', '   A'])
  })
  it('Single-Char', () => {
    Assert(Runtime.Token.Const('A', 'A'), ['A', ''])
    Assert(Runtime.Token.Const('A', 'A '), ['A', ' '])
    Assert(Runtime.Token.Const('A', 'AA'), ['A', 'A'])
    Assert(Runtime.Token.Const('A', 'AA '), ['A', 'A '])
  })
  it('Multi-Char', () => {
    Assert(Runtime.Token.Const('AB', 'AB'), ['AB', ''])
    Assert(Runtime.Token.Const('AB', 'AB '), ['AB', ' '])
    Assert(Runtime.Token.Const('AB', 'ABA'), ['AB', 'A'])
    Assert(Runtime.Token.Const('AB', 'ABA '), ['AB', 'A '])
  })
  it('Single-Char -> Ignore-Whitespace', () => {
    Assert(Runtime.Token.Const('A', '  A'), ['A', ''])
    Assert(Runtime.Token.Const('A', '  A '), ['A', ' '])
    Assert(Runtime.Token.Const('A', '  AA'), ['A', 'A'])
    Assert(Runtime.Token.Const('A', '  AA '), ['A', 'A '])
    Assert(Runtime.Token.Const('A', '\nAA '), ['A', 'A '])
    Assert(Runtime.Token.Const('A', ' \nAA '), ['A', 'A '])
    Assert(Runtime.Token.Const('A', '\n AA '), ['A', 'A '])
    Assert(Runtime.Token.Const('A', ' \n AA '), ['A', 'A '])
  })
  it('Multi-Char -> Ignore-Whitespace', () => {
    Assert(Runtime.Token.Const('AB', '  AB'), ['AB', ''])
    Assert(Runtime.Token.Const('AB', '  AB '), ['AB', ' '])
    Assert(Runtime.Token.Const('AB', '  ABA'), ['AB', 'A'])
    Assert(Runtime.Token.Const('AB', '  ABA '), ['AB', 'A '])
    Assert(Runtime.Token.Const('AB', '\nABA '), ['AB', 'A '])
    Assert(Runtime.Token.Const('AB', ' \nABA '), ['AB', 'A '])
    Assert(Runtime.Token.Const('AB', '\n ABA '), ['AB', 'A '])
    Assert(Runtime.Token.Const('AB', ' \n ABA '), ['AB', 'A '])
  })
  it('Single-Whitespace', () => {
    Assert(Runtime.Token.Const(' ', ''), [])
    Assert(Runtime.Token.Const(' ', ' '), [' ', ''])
    Assert(Runtime.Token.Const(' ', ' A'), [' ', 'A'])
    Assert(Runtime.Token.Const(' ', ' A '), [' ', 'A '])
    Assert(Runtime.Token.Const(' ', ' AA'), [' ', 'AA'])
    Assert(Runtime.Token.Const(' ', ' AA '), [' ', 'AA '])
  })
  it('Multi-Whitespace', () => {
    Assert(Runtime.Token.Const('  ', ''), [])
    Assert(Runtime.Token.Const('  ', ' '), [])
    Assert(Runtime.Token.Const('  ', '  A'), ['  ', 'A'])
    Assert(Runtime.Token.Const('  ', '  A '), ['  ', 'A '])
    Assert(Runtime.Token.Const('  ', '  AA'), ['  ', 'AA'])
    Assert(Runtime.Token.Const('  ', '  AA '), ['  ', 'AA '])
  })
  it('Newline', () => {
    Assert(Runtime.Token.Const('\n', ''), [])
    Assert(Runtime.Token.Const('\n', ' '), [])
    Assert(Runtime.Token.Const('\n', '\nA'), ['\n', 'A'])
    Assert(Runtime.Token.Const('\n', '  \nA '), ['\n', 'A '])
    Assert(Runtime.Token.Const('\n', '  \nAA'), ['\n', 'AA'])
    Assert(Runtime.Token.Const('\n', '  \nAA '), ['\n', 'AA '])
  })
  it('Newline-Single-Whitespace', () => {
    Assert(Runtime.Token.Const('\n ', ''), [])
    Assert(Runtime.Token.Const('\n ', ' '), [])
    Assert(Runtime.Token.Const('\n ', '\nA'), [])
    Assert(Runtime.Token.Const('\n ', '  \nA '), [])
    Assert(Runtime.Token.Const('\n ', '  \nAA'), [])
    Assert(Runtime.Token.Const('\n ', '  \nAA '), [])
    Assert(Runtime.Token.Const('\n ', '\n A'), ['\n ', 'A'])
    Assert(Runtime.Token.Const('\n ', '  \n A '), ['\n ', 'A '])
    Assert(Runtime.Token.Const('\n ', '  \n AA'), ['\n ', 'AA'])
    Assert(Runtime.Token.Const('\n ', '  \n AA '), ['\n ', 'AA '])
  })
  it('Newline-Multi-Whitespace', () => {
    Assert(Runtime.Token.Const('\n  ', ''), [])
    Assert(Runtime.Token.Const('\n  ', ' '), [])
    Assert(Runtime.Token.Const('\n  ', '\nA'), [])
    Assert(Runtime.Token.Const('\n  ', '  \nA '), [])
    Assert(Runtime.Token.Const('\n  ', '  \nAA'), [])
    Assert(Runtime.Token.Const('\n  ', '  \nAA '), [])
    Assert(Runtime.Token.Const('\n  ', '\n  A'), ['\n  ', 'A'])
    Assert(Runtime.Token.Const('\n  ', '  \n  A '), ['\n  ', 'A '])
    Assert(Runtime.Token.Const('\n  ', '  \n  AA'), ['\n  ', 'AA'])
    Assert(Runtime.Token.Const('\n  ', '  \n  AA '), ['\n  ', 'AA '])
  })
})
